# Generated by Django 2.2 on 2020-10-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_auto_20201027_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TvShow',
            new_name='Show',
        ),
    ]
