# Generated by Django 2.2 on 2020-10-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0003_auto_20201027_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
